name: Deploy NestJS to EC2

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy Project to EC2 via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}
        rm: true
        strip_components: 0

    - name: Upload .env File
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "${{ github.ref == 'refs/heads/main' && secrets.ENV_FILE || secrets.ENV_FILE_DEV }}" > ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}/.env

    - name: Run Remote Deployment Script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ github.ref == 'refs/heads/main' && secrets.PROJECT_PATH || secrets.PROJECT_PATH_DEV }}
          echo "Installing dependencies..."
          npm install

          APP_NAME="${{ github.ref == 'refs/heads/main' && 'nestjs-api' || 'nestjs-api-dev' }}"
          echo "Restarting $APP_NAME with PM2..."
          pm2 delete "$APP_NAME" || true
          pm2 start npm --name "$APP_NAME" -- run start
          pm2 save
